name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        SECRET_KEY: p*tsw(bh*x(f*1-#*@c^3sl^1l1g!cwe!)o5_p9k186vkmighi
        DEBUG: True
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test accounts 
        python manage.py test blog
